apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders
  template:
    metadata:
      labels:
        app: orders
    spec:
      containers:
        - name: orders
          image: QuintenWs/docker-compose-orders:latest
          ports:
            - containerPort: 8080
          env:
            - name: JAVA_OPTS
              value: "-XX:MaxRAMPercentage=75.0 -Djava.security.egd=file:/dev/urandom"
            - name: SERVER_TOMCAT_ACCESSLOG_ENABLED
              value: "true"
            - name: SPRING_PROFILES_ACTIVE
              value: mysql,activemq
            - name: SPRING_DATASOURCE_WRITER_URL
              value: jdbc:mysql://orders-db:3306/orders
            - name: SPRING_DATASOURCE_WRITER_USERNAME
              value: orders_user
            - name: SPRING_DATASOURCE_WRITER_PASSWORD
              value: default_password
            - name: SPRING_DATASOURCE_READER_URL
              value: jdbc:mysql://orders-db:3306/orders
            - name: SPRING_DATASOURCE_READER_USERNAME
              value: orders_user
            - name: SPRING_DATASOURCE_READER_PASSWORD
              value: default_password
            - name: SPRING_ACTIVEMQ_BROKERURL
              value: tcp://activemq:61616
          resources:
            limits:
              memory: "512Mi"
          securityContext:
            capabilities:
              drop:
                - ALL
---
apiVersion: v1
kind: Service
metadata:
  name: orders
spec:
  selector:
    app: orders
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080