apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
        - name: ui
          image: your-docker-repo/ui:latest
          ports:
            - containerPort: 8080
          env:
            - name: JAVA_OPTS
              value: "-XX:MaxRAMPercentage=75.0 -Djava.security.egd=file:/dev/urandom"
            - name: SERVER_TOMCAT_ACCESSLOG_ENABLED
              value: "true"
            - name: ENDPOINTS_CATALOG
              value: "http://catalog:8080"
            - name: ENDPOINTS_CARTS
              value: "http://carts:8080"
            - name: ENDPOINTS_ORDERS
              value: "http://orders:8080"
            - name: ENDPOINTS_CHECKOUT
              value: "http://checkout:8080"
            - name: ENDPOINTS_ASSETS
              value: "http://assets:8080"
          resources:
            limits:
              memory: "512Mi"
          securityContext:
            capabilities:
              drop:
                - ALL
---
apiVersion: v1
kind: Service
metadata:
  name: ui
spec:
  type: LoadBalancer
  selector:
    app: ui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080